/**
 * Curated list of S&P 500 stocks and popular ETFs
 * These assets are pre-verified and don't require API validation
 */

export interface CuratedAsset {
  symbol: string;
  name: string;
  type: "STOCK" | "ETF";
}

// S&P 500 Components (alphabetically sorted, includes ~500 stocks)
export const SP500_STOCKS: CuratedAsset[] = [
  { symbol: "A", name: "Agilent Technologies", type: "STOCK" },
  { symbol: "AAL", name: "American Airlines Group", type: "STOCK" },
  { symbol: "AAP", name: "Advance Auto Parts", type: "STOCK" },
  { symbol: "AAPL", name: "Apple Inc.", type: "STOCK" },
  { symbol: "ABBV", name: "AbbVie Inc.", type: "STOCK" },
  { symbol: "ABC", name: "AmerisourceBergen", type: "STOCK" },
  { symbol: "ABNB", name: "Airbnb Inc.", type: "STOCK" },
  { symbol: "ABT", name: "Abbott Laboratories", type: "STOCK" },
  { symbol: "ACGL", name: "Arch Capital Group", type: "STOCK" },
  { symbol: "ACN", name: "Accenture plc", type: "STOCK" },
  { symbol: "ADBE", name: "Adobe Inc.", type: "STOCK" },
  { symbol: "ADI", name: "Analog Devices", type: "STOCK" },
  { symbol: "ADM", name: "Archer-Daniels-Midland", type: "STOCK" },
  { symbol: "ADP", name: "Automatic Data Processing", type: "STOCK" },
  { symbol: "ADSK", name: "Autodesk Inc.", type: "STOCK" },
  { symbol: "AEE", name: "Ameren Corporation", type: "STOCK" },
  { symbol: "AEP", name: "American Electric Power", type: "STOCK" },
  { symbol: "AES", name: "AES Corporation", type: "STOCK" },
  { symbol: "AFL", name: "Aflac Inc.", type: "STOCK" },
  { symbol: "AIG", name: "American International Group", type: "STOCK" },
  { symbol: "AIZ", name: "Assurant Inc.", type: "STOCK" },
  { symbol: "AJG", name: "Arthur J. Gallagher & Co.", type: "STOCK" },
  { symbol: "AKAM", name: "Akamai Technologies", type: "STOCK" },
  { symbol: "ALB", name: "Albemarle Corporation", type: "STOCK" },
  { symbol: "ALGN", name: "Align Technology", type: "STOCK" },
  { symbol: "ALL", name: "Allstate Corporation", type: "STOCK" },
  { symbol: "ALLE", name: "Allegion plc", type: "STOCK" },
  { symbol: "AMAT", name: "Applied Materials", type: "STOCK" },
  { symbol: "AMCR", name: "Amcor plc", type: "STOCK" },
  { symbol: "AMD", name: "Advanced Micro Devices", type: "STOCK" },
  { symbol: "AME", name: "AMETEK Inc.", type: "STOCK" },
  { symbol: "AMGN", name: "Amgen Inc.", type: "STOCK" },
  { symbol: "AMP", name: "Ameriprise Financial", type: "STOCK" },
  { symbol: "AMT", name: "American Tower Corporation", type: "STOCK" },
  { symbol: "AMZN", name: "Amazon.com Inc.", type: "STOCK" },
  { symbol: "ANET", name: "Arista Networks", type: "STOCK" },
  { symbol: "ANSS", name: "ANSYS Inc.", type: "STOCK" },
  { symbol: "AON", name: "Aon plc", type: "STOCK" },
  { symbol: "AOS", name: "A.O. Smith Corporation", type: "STOCK" },
  { symbol: "APA", name: "APA Corporation", type: "STOCK" },
  { symbol: "APD", name: "Air Products and Chemicals", type: "STOCK" },
  { symbol: "APH", name: "Amphenol Corporation", type: "STOCK" },
  { symbol: "APTV", name: "Aptiv PLC", type: "STOCK" },
  { symbol: "ARE", name: "Alexandria Real Estate", type: "STOCK" },
  { symbol: "ATO", name: "Atmos Energy", type: "STOCK" },
  { symbol: "AVB", name: "AvalonBay Communities", type: "STOCK" },
  { symbol: "AVGO", name: "Broadcom Inc.", type: "STOCK" },
  { symbol: "AVY", name: "Avery Dennison", type: "STOCK" },
  { symbol: "AWK", name: "American Water Works", type: "STOCK" },
  { symbol: "AXON", name: "Axon Enterprise", type: "STOCK" },
  { symbol: "AXP", name: "American Express", type: "STOCK" },
  { symbol: "AZO", name: "AutoZone Inc.", type: "STOCK" },
  { symbol: "BA", name: "Boeing Company", type: "STOCK" },
  { symbol: "BAC", name: "Bank of America", type: "STOCK" },
  { symbol: "BALL", name: "Ball Corporation", type: "STOCK" },
  { symbol: "BAX", name: "Baxter International", type: "STOCK" },
  { symbol: "BBWI", name: "Bath & Body Works", type: "STOCK" },
  { symbol: "BBY", name: "Best Buy Co.", type: "STOCK" },
  { symbol: "BDX", name: "Becton Dickinson", type: "STOCK" },
  { symbol: "BEN", name: "Franklin Resources", type: "STOCK" },
  { symbol: "BF.B", name: "Brown-Forman Corporation", type: "STOCK" },
  { symbol: "BG", name: "Bunge Limited", type: "STOCK" },
  { symbol: "BIIB", name: "Biogen Inc.", type: "STOCK" },
  { symbol: "BIO", name: "Bio-Rad Laboratories", type: "STOCK" },
  { symbol: "BK", name: "Bank of New York Mellon", type: "STOCK" },
  { symbol: "BKNG", name: "Booking Holdings", type: "STOCK" },
  { symbol: "BKR", name: "Baker Hughes Company", type: "STOCK" },
  { symbol: "BLK", name: "BlackRock Inc.", type: "STOCK" },
  { symbol: "BMY", name: "Bristol-Myers Squibb", type: "STOCK" },
  { symbol: "BR", name: "Broadridge Financial", type: "STOCK" },
  { symbol: "BRK.B", name: "Berkshire Hathaway", type: "STOCK" },
  { symbol: "BRO", name: "Brown & Brown", type: "STOCK" },
  { symbol: "BSX", name: "Boston Scientific", type: "STOCK" },
  { symbol: "BWA", name: "BorgWarner Inc.", type: "STOCK" },
  { symbol: "BXP", name: "BXP Inc.", type: "STOCK" },
  { symbol: "C", name: "Citigroup Inc.", type: "STOCK" },
  { symbol: "CAG", name: "Conagra Brands", type: "STOCK" },
  { symbol: "CAH", name: "Cardinal Health", type: "STOCK" },
  { symbol: "CARR", name: "Carrier Global", type: "STOCK" },
  { symbol: "CAT", name: "Caterpillar Inc.", type: "STOCK" },
  { symbol: "CB", name: "Chubb Limited", type: "STOCK" },
  { symbol: "CBOE", name: "Cboe Global Markets", type: "STOCK" },
  { symbol: "CBRE", name: "CBRE Group", type: "STOCK" },
  { symbol: "CCI", name: "Crown Castle International", type: "STOCK" },
  { symbol: "CCL", name: "Carnival Corporation", type: "STOCK" },
  { symbol: "CDNS", name: "Cadence Design Systems", type: "STOCK" },
  { symbol: "CDW", name: "CDW Corporation", type: "STOCK" },
  { symbol: "CE", name: "Celanese Corporation", type: "STOCK" },
  { symbol: "CEG", name: "Constellation Energy", type: "STOCK" },
  { symbol: "CF", name: "CF Industries Holdings", type: "STOCK" },
  { symbol: "CFG", name: "Citizens Financial Group", type: "STOCK" },
  { symbol: "CHD", name: "Church & Dwight", type: "STOCK" },
  { symbol: "CHRW", name: "C.H. Robinson Worldwide", type: "STOCK" },
  { symbol: "CHTR", name: "Charter Communications", type: "STOCK" },
  { symbol: "CI", name: "Cigna Group", type: "STOCK" },
  { symbol: "CINF", name: "Cincinnati Financial", type: "STOCK" },
  { symbol: "CL", name: "Colgate-Palmolive", type: "STOCK" },
  { symbol: "CLX", name: "Clorox Company", type: "STOCK" },
  { symbol: "CMA", name: "Comerica Incorporated", type: "STOCK" },
  { symbol: "CMCSA", name: "Comcast Corporation", type: "STOCK" },
  { symbol: "CME", name: "CME Group Inc.", type: "STOCK" },
  { symbol: "CMG", name: "Chipotle Mexican Grill", type: "STOCK" },
  { symbol: "CMI", name: "Cummins Inc.", type: "STOCK" },
  { symbol: "CMS", name: "CMS Energy", type: "STOCK" },
  { symbol: "CNC", name: "Centene Corporation", type: "STOCK" },
  { symbol: "CNP", name: "CenterPoint Energy", type: "STOCK" },
  { symbol: "COF", name: "Capital One Financial", type: "STOCK" },
  { symbol: "COO", name: "Cooper Companies", type: "STOCK" },
  { symbol: "COP", name: "ConocoPhillips", type: "STOCK" },
  { symbol: "COR", name: "Cencora Inc.", type: "STOCK" },
  { symbol: "COST", name: "Costco Wholesale", type: "STOCK" },
  { symbol: "CPB", name: "Campbell Soup Company", type: "STOCK" },
  { symbol: "CPRT", name: "Copart Inc.", type: "STOCK" },
  { symbol: "CPT", name: "Camden Property Trust", type: "STOCK" },
  { symbol: "CRL", name: "Charles River Laboratories", type: "STOCK" },
  { symbol: "CRM", name: "Salesforce Inc.", type: "STOCK" },
  { symbol: "CSCO", name: "Cisco Systems", type: "STOCK" },
  { symbol: "CSGP", name: "CoStar Group", type: "STOCK" },
  { symbol: "CSX", name: "CSX Corporation", type: "STOCK" },
  { symbol: "CTAS", name: "Cintas Corporation", type: "STOCK" },
  { symbol: "CTLT", name: "Catalent Inc.", type: "STOCK" },
  { symbol: "CTRA", name: "Coterra Energy", type: "STOCK" },
  { symbol: "CTSH", name: "Cognizant Technology", type: "STOCK" },
  { symbol: "CTVA", name: "Corteva Inc.", type: "STOCK" },
  { symbol: "CVS", name: "CVS Health", type: "STOCK" },
  { symbol: "CVX", name: "Chevron Corporation", type: "STOCK" },
  { symbol: "CZR", name: "Caesars Entertainment", type: "STOCK" },
  { symbol: "D", name: "Dominion Energy", type: "STOCK" },
  { symbol: "DAL", name: "Delta Air Lines", type: "STOCK" },
  { symbol: "DD", name: "DuPont de Nemours", type: "STOCK" },
  { symbol: "DE", name: "Deere & Company", type: "STOCK" },
  { symbol: "DECK", name: "Deckers Outdoor", type: "STOCK" },
  { symbol: "DFS", name: "Discover Financial", type: "STOCK" },
  { symbol: "DG", name: "Dollar General", type: "STOCK" },
  { symbol: "DGX", name: "Quest Diagnostics", type: "STOCK" },
  { symbol: "DHI", name: "D.R. Horton", type: "STOCK" },
  { symbol: "DHR", name: "Danaher Corporation", type: "STOCK" },
  { symbol: "DIS", name: "Walt Disney Company", type: "STOCK" },
  { symbol: "DLR", name: "Digital Realty Trust", type: "STOCK" },
  { symbol: "DLTR", name: "Dollar Tree Inc.", type: "STOCK" },
  { symbol: "DOC", name: "Healthpeak Properties", type: "STOCK" },
  { symbol: "DOV", name: "Dover Corporation", type: "STOCK" },
  { symbol: "DOW", name: "Dow Inc.", type: "STOCK" },
  { symbol: "DPZ", name: "Domino's Pizza", type: "STOCK" },
  { symbol: "DRI", name: "Darden Restaurants", type: "STOCK" },
  { symbol: "DTE", name: "DTE Energy", type: "STOCK" },
  { symbol: "DUK", name: "Duke Energy", type: "STOCK" },
  { symbol: "DVA", name: "DaVita Inc.", type: "STOCK" },
  { symbol: "DVN", name: "Devon Energy", type: "STOCK" },
  { symbol: "DXCM", name: "DexCom Inc.", type: "STOCK" },
  { symbol: "EA", name: "Electronic Arts", type: "STOCK" },
  { symbol: "EBAY", name: "eBay Inc.", type: "STOCK" },
  { symbol: "ECL", name: "Ecolab Inc.", type: "STOCK" },
  { symbol: "ED", name: "Consolidated Edison", type: "STOCK" },
  { symbol: "EFX", name: "Equifax Inc.", type: "STOCK" },
  { symbol: "EG", name: "Everest Group", type: "STOCK" },
  { symbol: "EIX", name: "Edison International", type: "STOCK" },
  { symbol: "EL", name: "Estée Lauder Companies", type: "STOCK" },
  { symbol: "ELV", name: "Elevance Health", type: "STOCK" },
  { symbol: "EMN", name: "Eastman Chemical", type: "STOCK" },
  { symbol: "EMR", name: "Emerson Electric", type: "STOCK" },
  { symbol: "ENPH", name: "Enphase Energy", type: "STOCK" },
  { symbol: "EOG", name: "EOG Resources", type: "STOCK" },
  { symbol: "EPAM", name: "EPAM Systems", type: "STOCK" },
  { symbol: "EQIX", name: "Equinix Inc.", type: "STOCK" },
  { symbol: "EQR", name: "Equity Residential", type: "STOCK" },
  { symbol: "EQT", name: "EQT Corporation", type: "STOCK" },
  { symbol: "ES", name: "Eversource Energy", type: "STOCK" },
  { symbol: "ESS", name: "Essex Property Trust", type: "STOCK" },
  { symbol: "ETN", name: "Eaton Corporation", type: "STOCK" },
  { symbol: "ETR", name: "Entergy Corporation", type: "STOCK" },
  { symbol: "ETSY", name: "Etsy Inc.", type: "STOCK" },
  { symbol: "EVRG", name: "Evergy Inc.", type: "STOCK" },
  { symbol: "EW", name: "Edwards Lifesciences", type: "STOCK" },
  { symbol: "EXC", name: "Exelon Corporation", type: "STOCK" },
  { symbol: "EXPD", name: "Expeditors International", type: "STOCK" },
  { symbol: "EXPE", name: "Expedia Group", type: "STOCK" },
  { symbol: "EXR", name: "Extra Space Storage", type: "STOCK" },
  { symbol: "F", name: "Ford Motor Company", type: "STOCK" },
  { symbol: "FANG", name: "Diamondback Energy", type: "STOCK" },
  { symbol: "FAST", name: "Fastenal Company", type: "STOCK" },
  { symbol: "FCX", name: "Freeport-McMoRan", type: "STOCK" },
  { symbol: "FDS", name: "FactSet Research Systems", type: "STOCK" },
  { symbol: "FDX", name: "FedEx Corporation", type: "STOCK" },
  { symbol: "FE", name: "FirstEnergy Corp.", type: "STOCK" },
  { symbol: "FFIV", name: "F5 Inc.", type: "STOCK" },
  { symbol: "FI", name: "Fiserv Inc.", type: "STOCK" },
  { symbol: "FICO", name: "Fair Isaac Corporation", type: "STOCK" },
  { symbol: "FIS", name: "Fidelity National Information", type: "STOCK" },
  { symbol: "FITB", name: "Fifth Third Bancorp", type: "STOCK" },
  { symbol: "FLT", name: "Fleetcor Technologies", type: "STOCK" },
  { symbol: "FMC", name: "FMC Corporation", type: "STOCK" },
  { symbol: "FOX", name: "Fox Corporation", type: "STOCK" },
  { symbol: "FOXA", name: "Fox Corporation Class A", type: "STOCK" },
  { symbol: "FRT", name: "Federal Realty Investment", type: "STOCK" },
  { symbol: "FSLR", name: "First Solar Inc.", type: "STOCK" },
  { symbol: "FTNT", name: "Fortinet Inc.", type: "STOCK" },
  { symbol: "FTV", name: "Fortive Corporation", type: "STOCK" },
  { symbol: "GD", name: "General Dynamics", type: "STOCK" },
  { symbol: "GE", name: "General Electric", type: "STOCK" },
  { symbol: "GEHC", name: "GE HealthCare Technologies", type: "STOCK" },
  { symbol: "GEN", name: "Gen Digital Inc.", type: "STOCK" },
  { symbol: "GILD", name: "Gilead Sciences", type: "STOCK" },
  { symbol: "GIS", name: "General Mills", type: "STOCK" },
  { symbol: "GL", name: "Globe Life Inc.", type: "STOCK" },
  { symbol: "GLW", name: "Corning Incorporated", type: "STOCK" },
  { symbol: "GM", name: "General Motors", type: "STOCK" },
  { symbol: "GNRC", name: "Generac Holdings", type: "STOCK" },
  { symbol: "GOOG", name: "Alphabet Inc. Class C", type: "STOCK" },
  { symbol: "GOOGL", name: "Alphabet Inc. Class A", type: "STOCK" },
  { symbol: "GPC", name: "Genuine Parts Company", type: "STOCK" },
  { symbol: "GPN", name: "Global Payments", type: "STOCK" },
  { symbol: "GRMN", name: "Garmin Ltd.", type: "STOCK" },
  { symbol: "GS", name: "Goldman Sachs Group", type: "STOCK" },
  { symbol: "GWW", name: "W.W. Grainger", type: "STOCK" },
  { symbol: "HAL", name: "Halliburton Company", type: "STOCK" },
  { symbol: "HAS", name: "Hasbro Inc.", type: "STOCK" },
  { symbol: "HBAN", name: "Huntington Bancshares", type: "STOCK" },
  { symbol: "HCA", name: "HCA Healthcare", type: "STOCK" },
  { symbol: "HD", name: "Home Depot", type: "STOCK" },
  { symbol: "HES", name: "Hess Corporation", type: "STOCK" },
  { symbol: "HIG", name: "Hartford Financial", type: "STOCK" },
  { symbol: "HII", name: "Huntington Ingalls Industries", type: "STOCK" },
  { symbol: "HLT", name: "Hilton Worldwide", type: "STOCK" },
  { symbol: "HOLX", name: "Hologic Inc.", type: "STOCK" },
  { symbol: "HON", name: "Honeywell International", type: "STOCK" },
  { symbol: "HPE", name: "Hewlett Packard Enterprise", type: "STOCK" },
  { symbol: "HPQ", name: "HP Inc.", type: "STOCK" },
  { symbol: "HRL", name: "Hormel Foods", type: "STOCK" },
  { symbol: "HSIC", name: "Henry Schein Inc.", type: "STOCK" },
  { symbol: "HST", name: "Host Hotels & Resorts", type: "STOCK" },
  { symbol: "HSY", name: "Hershey Company", type: "STOCK" },
  { symbol: "HUBB", name: "Hubbell Incorporated", type: "STOCK" },
  { symbol: "HUM", name: "Humana Inc.", type: "STOCK" },
  { symbol: "HWM", name: "Howmet Aerospace", type: "STOCK" },
  { symbol: "IBM", name: "International Business Machines", type: "STOCK" },
  { symbol: "ICE", name: "Intercontinental Exchange", type: "STOCK" },
  { symbol: "IDXX", name: "IDEXX Laboratories", type: "STOCK" },
  { symbol: "IEX", name: "IDEX Corporation", type: "STOCK" },
  { symbol: "IFF", name: "International Flavors & Fragrances", type: "STOCK" },
  { symbol: "ILMN", name: "Illumina Inc.", type: "STOCK" },
  { symbol: "INCY", name: "Incyte Corporation", type: "STOCK" },
  { symbol: "INTC", name: "Intel Corporation", type: "STOCK" },
  { symbol: "INTU", name: "Intuit Inc.", type: "STOCK" },
  { symbol: "INVH", name: "Invitation Homes", type: "STOCK" },
  { symbol: "IP", name: "International Paper", type: "STOCK" },
  { symbol: "IPG", name: "Interpublic Group", type: "STOCK" },
  { symbol: "IQV", name: "IQVIA Holdings", type: "STOCK" },
  { symbol: "IR", name: "Ingersoll Rand", type: "STOCK" },
  { symbol: "IRM", name: "Iron Mountain", type: "STOCK" },
  { symbol: "ISRG", name: "Intuitive Surgical", type: "STOCK" },
  { symbol: "IT", name: "Gartner Inc.", type: "STOCK" },
  { symbol: "ITW", name: "Illinois Tool Works", type: "STOCK" },
  { symbol: "IVZ", name: "Invesco Ltd.", type: "STOCK" },
  { symbol: "J", name: "Jacobs Solutions", type: "STOCK" },
  { symbol: "JBHT", name: "J.B. Hunt Transport", type: "STOCK" },
  { symbol: "JCI", name: "Johnson Controls International", type: "STOCK" },
  { symbol: "JKHY", name: "Jack Henry & Associates", type: "STOCK" },
  { symbol: "JNJ", name: "Johnson & Johnson", type: "STOCK" },
  { symbol: "JNPR", name: "Juniper Networks", type: "STOCK" },
  { symbol: "JPM", name: "JPMorgan Chase & Co.", type: "STOCK" },
  { symbol: "K", name: "Kellanova", type: "STOCK" },
  { symbol: "KDP", name: "Keurig Dr Pepper", type: "STOCK" },
  { symbol: "KEY", name: "KeyCorp", type: "STOCK" },
  { symbol: "KEYS", name: "Keysight Technologies", type: "STOCK" },
  { symbol: "KHC", name: "Kraft Heinz Company", type: "STOCK" },
  { symbol: "KIM", name: "Kimco Realty", type: "STOCK" },
  { symbol: "KLAC", name: "KLA Corporation", type: "STOCK" },
  { symbol: "KMB", name: "Kimberly-Clark", type: "STOCK" },
  { symbol: "KMI", name: "Kinder Morgan", type: "STOCK" },
  { symbol: "KMX", name: "CarMax Inc.", type: "STOCK" },
  { symbol: "KO", name: "Coca-Cola Company", type: "STOCK" },
  { symbol: "KR", name: "Kroger Company", type: "STOCK" },
  { symbol: "KVUE", name: "Kenvue Inc.", type: "STOCK" },
  { symbol: "L", name: "Loews Corporation", type: "STOCK" },
  { symbol: "LDOS", name: "Leidos Holdings", type: "STOCK" },
  { symbol: "LEN", name: "Lennar Corporation", type: "STOCK" },
  { symbol: "LH", name: "Labcorp Holdings", type: "STOCK" },
  { symbol: "LHX", name: "L3Harris Technologies", type: "STOCK" },
  { symbol: "LIN", name: "Linde plc", type: "STOCK" },
  { symbol: "LKQ", name: "LKQ Corporation", type: "STOCK" },
  { symbol: "LLY", name: "Eli Lilly and Company", type: "STOCK" },
  { symbol: "LMT", name: "Lockheed Martin", type: "STOCK" },
  { symbol: "LNT", name: "Alliant Energy", type: "STOCK" },
  { symbol: "LOW", name: "Lowe's Companies", type: "STOCK" },
  { symbol: "LRCX", name: "Lam Research", type: "STOCK" },
  { symbol: "LULU", name: "Lululemon Athletica", type: "STOCK" },
  { symbol: "LUV", name: "Southwest Airlines", type: "STOCK" },
  { symbol: "LVS", name: "Las Vegas Sands", type: "STOCK" },
  { symbol: "LW", name: "Lamb Weston Holdings", type: "STOCK" },
  { symbol: "LYB", name: "LyondellBasell Industries", type: "STOCK" },
  { symbol: "LYV", name: "Live Nation Entertainment", type: "STOCK" },
  { symbol: "MA", name: "Mastercard Incorporated", type: "STOCK" },
  { symbol: "MAA", name: "Mid-America Apartment", type: "STOCK" },
  { symbol: "MAR", name: "Marriott International", type: "STOCK" },
  { symbol: "MAS", name: "Masco Corporation", type: "STOCK" },
  { symbol: "MCD", name: "McDonald's Corporation", type: "STOCK" },
  { symbol: "MCHP", name: "Microchip Technology", type: "STOCK" },
  { symbol: "MCK", name: "McKesson Corporation", type: "STOCK" },
  { symbol: "MCO", name: "Moody's Corporation", type: "STOCK" },
  { symbol: "MDLZ", name: "Mondelez International", type: "STOCK" },
  { symbol: "MDT", name: "Medtronic plc", type: "STOCK" },
  { symbol: "MET", name: "MetLife Inc.", type: "STOCK" },
  { symbol: "META", name: "Meta Platforms", type: "STOCK" },
  { symbol: "MGM", name: "MGM Resorts International", type: "STOCK" },
  { symbol: "MHK", name: "Mohawk Industries", type: "STOCK" },
  { symbol: "MKC", name: "McCormick & Company", type: "STOCK" },
  { symbol: "MKTX", name: "MarketAxess Holdings", type: "STOCK" },
  { symbol: "MLM", name: "Martin Marietta Materials", type: "STOCK" },
  { symbol: "MMC", name: "Marsh & McLennan", type: "STOCK" },
  { symbol: "MMM", name: "3M Company", type: "STOCK" },
  { symbol: "MNST", name: "Monster Beverage", type: "STOCK" },
  { symbol: "MO", name: "Altria Group", type: "STOCK" },
  { symbol: "MOH", name: "Molina Healthcare", type: "STOCK" },
  { symbol: "MOS", name: "Mosaic Company", type: "STOCK" },
  { symbol: "MPC", name: "Marathon Petroleum", type: "STOCK" },
  { symbol: "MPWR", name: "Monolithic Power Systems", type: "STOCK" },
  { symbol: "MRK", name: "Merck & Co.", type: "STOCK" },
  { symbol: "MRNA", name: "Moderna Inc.", type: "STOCK" },
  { symbol: "MRO", name: "Marathon Oil", type: "STOCK" },
  { symbol: "MS", name: "Morgan Stanley", type: "STOCK" },
  { symbol: "MSCI", name: "MSCI Inc.", type: "STOCK" },
  { symbol: "MSFT", name: "Microsoft Corporation", type: "STOCK" },
  { symbol: "MSI", name: "Motorola Solutions", type: "STOCK" },
  { symbol: "MTB", name: "M&T Bank Corporation", type: "STOCK" },
  { symbol: "MTCH", name: "Match Group", type: "STOCK" },
  { symbol: "MTD", name: "Mettler-Toledo International", type: "STOCK" },
  { symbol: "MU", name: "Micron Technology", type: "STOCK" },
  { symbol: "NCLH", name: "Norwegian Cruise Line", type: "STOCK" },
  { symbol: "NDAQ", name: "Nasdaq Inc.", type: "STOCK" },
  { symbol: "NDSN", name: "Nordson Corporation", type: "STOCK" },
  { symbol: "NEE", name: "NextEra Energy", type: "STOCK" },
  { symbol: "NEM", name: "Newmont Corporation", type: "STOCK" },
  { symbol: "NFLX", name: "Netflix Inc.", type: "STOCK" },
  { symbol: "NI", name: "NiSource Inc.", type: "STOCK" },
  { symbol: "NKE", name: "Nike Inc.", type: "STOCK" },
  { symbol: "NOC", name: "Northrop Grumman", type: "STOCK" },
  { symbol: "NOW", name: "ServiceNow Inc.", type: "STOCK" },
  { symbol: "NRG", name: "NRG Energy", type: "STOCK" },
  { symbol: "NSC", name: "Norfolk Southern", type: "STOCK" },
  { symbol: "NTAP", name: "NetApp Inc.", type: "STOCK" },
  { symbol: "NTRS", name: "Northern Trust", type: "STOCK" },
  { symbol: "NUE", name: "Nucor Corporation", type: "STOCK" },
  { symbol: "NVDA", name: "NVIDIA Corporation", type: "STOCK" },
  { symbol: "NVR", name: "NVR Inc.", type: "STOCK" },
  { symbol: "NWS", name: "News Corporation", type: "STOCK" },
  { symbol: "NWSA", name: "News Corporation Class A", type: "STOCK" },
  { symbol: "NXPI", name: "NXP Semiconductors", type: "STOCK" },
  { symbol: "O", name: "Realty Income", type: "STOCK" },
  { symbol: "ODFL", name: "Old Dominion Freight Line", type: "STOCK" },
  { symbol: "OKE", name: "ONEOK Inc.", type: "STOCK" },
  { symbol: "OMC", name: "Omnicom Group", type: "STOCK" },
  { symbol: "ON", name: "ON Semiconductor", type: "STOCK" },
  { symbol: "ORCL", name: "Oracle Corporation", type: "STOCK" },
  { symbol: "ORLY", name: "O'Reilly Automotive", type: "STOCK" },
  { symbol: "OTIS", name: "Otis Worldwide", type: "STOCK" },
  { symbol: "OXY", name: "Occidental Petroleum", type: "STOCK" },
  { symbol: "PANW", name: "Palo Alto Networks", type: "STOCK" },
  { symbol: "PARA", name: "Paramount Global", type: "STOCK" },
  { symbol: "PAYC", name: "Paycom Software", type: "STOCK" },
  { symbol: "PAYX", name: "Paychex Inc.", type: "STOCK" },
  { symbol: "PCAR", name: "PACCAR Inc.", type: "STOCK" },
  { symbol: "PCG", name: "PG&E Corporation", type: "STOCK" },
  { symbol: "PEG", name: "Public Service Enterprise", type: "STOCK" },
  { symbol: "PEP", name: "PepsiCo Inc.", type: "STOCK" },
  { symbol: "PFE", name: "Pfizer Inc.", type: "STOCK" },
  { symbol: "PFG", name: "Principal Financial Group", type: "STOCK" },
  { symbol: "PG", name: "Procter & Gamble", type: "STOCK" },
  { symbol: "PGR", name: "Progressive Corporation", type: "STOCK" },
  { symbol: "PH", name: "Parker-Hannifin", type: "STOCK" },
  { symbol: "PHM", name: "PulteGroup Inc.", type: "STOCK" },
  { symbol: "PKG", name: "Packaging Corporation", type: "STOCK" },
  { symbol: "PLD", name: "Prologis Inc.", type: "STOCK" },
  { symbol: "PM", name: "Philip Morris International", type: "STOCK" },
  { symbol: "PNC", name: "PNC Financial Services", type: "STOCK" },
  { symbol: "PNR", name: "Pentair plc", type: "STOCK" },
  { symbol: "PNW", name: "Pinnacle West Capital", type: "STOCK" },
  { symbol: "PODD", name: "Insulet Corporation", type: "STOCK" },
  { symbol: "POOL", name: "Pool Corporation", type: "STOCK" },
  { symbol: "PPG", name: "PPG Industries", type: "STOCK" },
  { symbol: "PPL", name: "PPL Corporation", type: "STOCK" },
  { symbol: "PRU", name: "Prudential Financial", type: "STOCK" },
  { symbol: "PSA", name: "Public Storage", type: "STOCK" },
  { symbol: "PSX", name: "Phillips 66", type: "STOCK" },
  { symbol: "PTC", name: "PTC Inc.", type: "STOCK" },
  { symbol: "PWR", name: "Quanta Services", type: "STOCK" },
  { symbol: "PXD", name: "Pioneer Natural Resources", type: "STOCK" },
  { symbol: "PYPL", name: "PayPal Holdings", type: "STOCK" },
  { symbol: "QCOM", name: "Qualcomm Incorporated", type: "STOCK" },
  { symbol: "QRVO", name: "Qorvo Inc.", type: "STOCK" },
  { symbol: "RCL", name: "Royal Caribbean Cruises", type: "STOCK" },
  { symbol: "REG", name: "Regency Centers", type: "STOCK" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals", type: "STOCK" },
  { symbol: "RF", name: "Regions Financial", type: "STOCK" },
  { symbol: "RJF", name: "Raymond James Financial", type: "STOCK" },
  { symbol: "RL", name: "Ralph Lauren Corporation", type: "STOCK" },
  { symbol: "RMD", name: "ResMed Inc.", type: "STOCK" },
  { symbol: "ROK", name: "Rockwell Automation", type: "STOCK" },
  { symbol: "ROL", name: "Rollins Inc.", type: "STOCK" },
  { symbol: "ROP", name: "Roper Technologies", type: "STOCK" },
  { symbol: "ROST", name: "Ross Stores", type: "STOCK" },
  { symbol: "RSG", name: "Republic Services", type: "STOCK" },
  { symbol: "RTX", name: "RTX Corporation", type: "STOCK" },
  { symbol: "RVTY", name: "Revvity Inc.", type: "STOCK" },
  { symbol: "SBAC", name: "SBA Communications", type: "STOCK" },
  { symbol: "SBUX", name: "Starbucks Corporation", type: "STOCK" },
  { symbol: "SCHW", name: "Charles Schwab", type: "STOCK" },
  { symbol: "SHW", name: "Sherwin-Williams", type: "STOCK" },
  { symbol: "SJM", name: "J.M. Smucker Company", type: "STOCK" },
  { symbol: "SLB", name: "Schlumberger Limited", type: "STOCK" },
  { symbol: "SMCI", name: "Super Micro Computer", type: "STOCK" },
  { symbol: "SNA", name: "Snap-on Incorporated", type: "STOCK" },
  { symbol: "SNPS", name: "Synopsys Inc.", type: "STOCK" },
  { symbol: "SO", name: "Southern Company", type: "STOCK" },
  { symbol: "SPG", name: "Simon Property Group", type: "STOCK" },
  { symbol: "SPGI", name: "S&P Global Inc.", type: "STOCK" },
  { symbol: "SRE", name: "Sempra", type: "STOCK" },
  { symbol: "STE", name: "STERIS plc", type: "STOCK" },
  { symbol: "STLD", name: "Steel Dynamics", type: "STOCK" },
  { symbol: "STT", name: "State Street Corporation", type: "STOCK" },
  { symbol: "STX", name: "Seagate Technology", type: "STOCK" },
  { symbol: "STZ", name: "Constellation Brands", type: "STOCK" },
  { symbol: "SWK", name: "Stanley Black & Decker", type: "STOCK" },
  { symbol: "SWKS", name: "Skyworks Solutions", type: "STOCK" },
  { symbol: "SYF", name: "Synchrony Financial", type: "STOCK" },
  { symbol: "SYK", name: "Stryker Corporation", type: "STOCK" },
  { symbol: "SYY", name: "Sysco Corporation", type: "STOCK" },
  { symbol: "T", name: "AT&T Inc.", type: "STOCK" },
  { symbol: "TAP", name: "Molson Coors Beverage", type: "STOCK" },
  { symbol: "TDG", name: "TransDigm Group", type: "STOCK" },
  { symbol: "TDY", name: "Teledyne Technologies", type: "STOCK" },
  { symbol: "TECH", name: "Bio-Techne Corporation", type: "STOCK" },
  { symbol: "TEL", name: "TE Connectivity", type: "STOCK" },
  { symbol: "TER", name: "Teradyne Inc.", type: "STOCK" },
  { symbol: "TFC", name: "Truist Financial", type: "STOCK" },
  { symbol: "TFX", name: "Teleflex Incorporated", type: "STOCK" },
  { symbol: "TGT", name: "Target Corporation", type: "STOCK" },
  { symbol: "TJX", name: "TJX Companies", type: "STOCK" },
  { symbol: "TMO", name: "Thermo Fisher Scientific", type: "STOCK" },
  { symbol: "TMUS", name: "T-Mobile US", type: "STOCK" },
  { symbol: "TPR", name: "Tapestry Inc.", type: "STOCK" },
  { symbol: "TRGP", name: "Targa Resources", type: "STOCK" },
  { symbol: "TRMB", name: "Trimble Inc.", type: "STOCK" },
  { symbol: "TROW", name: "T. Rowe Price Group", type: "STOCK" },
  { symbol: "TRV", name: "Travelers Companies", type: "STOCK" },
  { symbol: "TSCO", name: "Tractor Supply Company", type: "STOCK" },
  { symbol: "TSLA", name: "Tesla Inc.", type: "STOCK" },
  { symbol: "TSN", name: "Tyson Foods", type: "STOCK" },
  { symbol: "TT", name: "Trane Technologies", type: "STOCK" },
  { symbol: "TTWO", name: "Take-Two Interactive", type: "STOCK" },
  { symbol: "TXN", name: "Texas Instruments", type: "STOCK" },
  { symbol: "TXT", name: "Textron Inc.", type: "STOCK" },
  { symbol: "TYL", name: "Tyler Technologies", type: "STOCK" },
  { symbol: "UAL", name: "United Airlines Holdings", type: "STOCK" },
  { symbol: "UBER", name: "Uber Technologies", type: "STOCK" },
  { symbol: "UDR", name: "UDR Inc.", type: "STOCK" },
  { symbol: "UHS", name: "Universal Health Services", type: "STOCK" },
  { symbol: "ULTA", name: "Ulta Beauty", type: "STOCK" },
  { symbol: "UNH", name: "UnitedHealth Group", type: "STOCK" },
  { symbol: "UNP", name: "Union Pacific", type: "STOCK" },
  { symbol: "UPS", name: "United Parcel Service", type: "STOCK" },
  { symbol: "URI", name: "United Rentals", type: "STOCK" },
  { symbol: "USB", name: "U.S. Bancorp", type: "STOCK" },
  { symbol: "V", name: "Visa Inc.", type: "STOCK" },
  { symbol: "VFC", name: "VF Corporation", type: "STOCK" },
  { symbol: "VICI", name: "VICI Properties", type: "STOCK" },
  { symbol: "VLO", name: "Valero Energy", type: "STOCK" },
  { symbol: "VLTO", name: "Veralto Corporation", type: "STOCK" },
  { symbol: "VMC", name: "Vulcan Materials", type: "STOCK" },
  { symbol: "VRSK", name: "Verisk Analytics", type: "STOCK" },
  { symbol: "VRSN", name: "VeriSign Inc.", type: "STOCK" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals", type: "STOCK" },
  { symbol: "VTR", name: "Ventas Inc.", type: "STOCK" },
  { symbol: "VTRS", name: "Viatris Inc.", type: "STOCK" },
  { symbol: "VZ", name: "Verizon Communications", type: "STOCK" },
  { symbol: "WAB", name: "Westinghouse Air Brake", type: "STOCK" },
  { symbol: "WAT", name: "Waters Corporation", type: "STOCK" },
  { symbol: "WBA", name: "Walgreens Boots Alliance", type: "STOCK" },
  { symbol: "WBD", name: "Warner Bros. Discovery", type: "STOCK" },
  { symbol: "WDC", name: "Western Digital", type: "STOCK" },
  { symbol: "WEC", name: "WEC Energy Group", type: "STOCK" },
  { symbol: "WELL", name: "Welltower Inc.", type: "STOCK" },
  { symbol: "WFC", name: "Wells Fargo & Company", type: "STOCK" },
  { symbol: "WHR", name: "Whirlpool Corporation", type: "STOCK" },
  { symbol: "WM", name: "Waste Management", type: "STOCK" },
  { symbol: "WMB", name: "Williams Companies", type: "STOCK" },
  { symbol: "WMT", name: "Walmart Inc.", type: "STOCK" },
  { symbol: "WRB", name: "W. R. Berkley Corporation", type: "STOCK" },
  { symbol: "WRK", name: "WestRock Company", type: "STOCK" },
  { symbol: "WST", name: "West Pharmaceutical", type: "STOCK" },
  { symbol: "WTW", name: "Willis Towers Watson", type: "STOCK" },
  { symbol: "WY", name: "Weyerhaeuser Company", type: "STOCK" },
  { symbol: "WYNN", name: "Wynn Resorts", type: "STOCK" },
  { symbol: "XEL", name: "Xcel Energy", type: "STOCK" },
  { symbol: "XOM", name: "Exxon Mobil", type: "STOCK" },
  { symbol: "XRAY", name: "Dentsply Sirona", type: "STOCK" },
  { symbol: "XYL", name: "Xylem Inc.", type: "STOCK" },
  { symbol: "YUM", name: "Yum! Brands", type: "STOCK" },
  { symbol: "ZBH", name: "Zimmer Biomet Holdings", type: "STOCK" },
  { symbol: "ZBRA", name: "Zebra Technologies", type: "STOCK" },
  { symbol: "ZTS", name: "Zoetis Inc.", type: "STOCK" },
];

// Popular ETFs (comprehensive list)
export const POPULAR_ETFS: CuratedAsset[] = [
  // Broad Market ETFs
  { symbol: "SPY", name: "SPDR S&P 500 ETF Trust", type: "ETF" },
  { symbol: "VOO", name: "Vanguard S&P 500 ETF", type: "ETF" },
  { symbol: "IVV", name: "iShares Core S&P 500 ETF", type: "ETF" },
  { symbol: "VTI", name: "Vanguard Total Stock Market ETF", type: "ETF" },
  { symbol: "QQQ", name: "Invesco QQQ Trust", type: "ETF" },
  { symbol: "IWM", name: "iShares Russell 2000 ETF", type: "ETF" },
  { symbol: "IWF", name: "iShares Russell 1000 Growth ETF", type: "ETF" },
  { symbol: "IWD", name: "iShares Russell 1000 Value ETF", type: "ETF" },
  { symbol: "VIG", name: "Vanguard Dividend Appreciation ETF", type: "ETF" },
  { symbol: "VYM", name: "Vanguard High Dividend Yield ETF", type: "ETF" },
  { symbol: "SCHD", name: "Schwab US Dividend Equity ETF", type: "ETF" },
  { symbol: "DGRO", name: "iShares Core Dividend Growth ETF", type: "ETF" },
  { symbol: "DVY", name: "iShares Select Dividend ETF", type: "ETF" },
  { symbol: "VUG", name: "Vanguard Growth ETF", type: "ETF" },
  { symbol: "VTV", name: "Vanguard Value ETF", type: "ETF" },
  { symbol: "MGK", name: "Vanguard Mega Cap Growth ETF", type: "ETF" },
  { symbol: "ITOT", name: "iShares Core S&P Total U.S. Stock Market ETF", type: "ETF" },
  { symbol: "SCHA", name: "Schwab U.S. Small-Cap ETF", type: "ETF" },
  { symbol: "SCHX", name: "Schwab U.S. Large-Cap ETF", type: "ETF" },
  { symbol: "SCHG", name: "Schwab U.S. Large-Cap Growth ETF", type: "ETF" },
  { symbol: "SCHV", name: "Schwab U.S. Large-Cap Value ETF", type: "ETF" },

  // Sector ETFs
  { symbol: "XLF", name: "Financial Select Sector SPDR Fund", type: "ETF" },
  { symbol: "XLK", name: "Technology Select Sector SPDR Fund", type: "ETF" },
  { symbol: "XLE", name: "Energy Select Sector SPDR Fund", type: "ETF" },
  { symbol: "XLV", name: "Health Care Select Sector SPDR Fund", type: "ETF" },
  { symbol: "XLI", name: "Industrial Select Sector SPDR Fund", type: "ETF" },
  { symbol: "XLY", name: "Consumer Discretionary Select Sector SPDR Fund", type: "ETF" },
  { symbol: "XLP", name: "Consumer Staples Select Sector SPDR Fund", type: "ETF" },
  { symbol: "XLU", name: "Utilities Select Sector SPDR Fund", type: "ETF" },
  { symbol: "XLB", name: "Materials Select Sector SPDR Fund", type: "ETF" },
  { symbol: "XLRE", name: "Real Estate Select Sector SPDR Fund", type: "ETF" },
  { symbol: "XLC", name: "Communication Services Select Sector SPDR Fund", type: "ETF" },
  { symbol: "VGT", name: "Vanguard Information Technology ETF", type: "ETF" },
  { symbol: "VHT", name: "Vanguard Health Care ETF", type: "ETF" },
  { symbol: "VFH", name: "Vanguard Financials ETF", type: "ETF" },
  { symbol: "VDE", name: "Vanguard Energy ETF", type: "ETF" },
  { symbol: "VIS", name: "Vanguard Industrials ETF", type: "ETF" },
  { symbol: "VCR", name: "Vanguard Consumer Discretionary ETF", type: "ETF" },
  { symbol: "VDC", name: "Vanguard Consumer Staples ETF", type: "ETF" },
  { symbol: "VAW", name: "Vanguard Materials ETF", type: "ETF" },
  { symbol: "VNQ", name: "Vanguard Real Estate ETF", type: "ETF" },
  { symbol: "VPU", name: "Vanguard Utilities ETF", type: "ETF" },

  // International ETFs
  { symbol: "VXUS", name: "Vanguard Total International Stock ETF", type: "ETF" },
  { symbol: "VEA", name: "Vanguard FTSE Developed Markets ETF", type: "ETF" },
  { symbol: "VWO", name: "Vanguard FTSE Emerging Markets ETF", type: "ETF" },
  { symbol: "EFA", name: "iShares MSCI EAFE ETF", type: "ETF" },
  { symbol: "EEM", name: "iShares MSCI Emerging Markets ETF", type: "ETF" },
  { symbol: "IEFA", name: "iShares Core MSCI EAFE ETF", type: "ETF" },
  { symbol: "IEMG", name: "iShares Core MSCI Emerging Markets ETF", type: "ETF" },
  { symbol: "SCHF", name: "Schwab International Equity ETF", type: "ETF" },
  { symbol: "SCHE", name: "Schwab Emerging Markets Equity ETF", type: "ETF" },
  { symbol: "VGK", name: "Vanguard FTSE Europe ETF", type: "ETF" },
  { symbol: "VPL", name: "Vanguard FTSE Pacific ETF", type: "ETF" },
  { symbol: "MCHI", name: "iShares MSCI China ETF", type: "ETF" },
  { symbol: "FXI", name: "iShares China Large-Cap ETF", type: "ETF" },
  { symbol: "EWJ", name: "iShares MSCI Japan ETF", type: "ETF" },
  { symbol: "EWZ", name: "iShares MSCI Brazil ETF", type: "ETF" },
  { symbol: "INDA", name: "iShares MSCI India ETF", type: "ETF" },

  // Bond ETFs
  { symbol: "BND", name: "Vanguard Total Bond Market ETF", type: "ETF" },
  { symbol: "AGG", name: "iShares Core U.S. Aggregate Bond ETF", type: "ETF" },
  { symbol: "LQD", name: "iShares iBoxx $ Investment Grade Corporate Bond ETF", type: "ETF" },
  { symbol: "HYG", name: "iShares iBoxx $ High Yield Corporate Bond ETF", type: "ETF" },
  { symbol: "JNK", name: "SPDR Bloomberg High Yield Bond ETF", type: "ETF" },
  { symbol: "TLT", name: "iShares 20+ Year Treasury Bond ETF", type: "ETF" },
  { symbol: "IEF", name: "iShares 7-10 Year Treasury Bond ETF", type: "ETF" },
  { symbol: "SHY", name: "iShares 1-3 Year Treasury Bond ETF", type: "ETF" },
  { symbol: "TIP", name: "iShares TIPS Bond ETF", type: "ETF" },
  { symbol: "VCIT", name: "Vanguard Intermediate-Term Corporate Bond ETF", type: "ETF" },
  { symbol: "VCSH", name: "Vanguard Short-Term Corporate Bond ETF", type: "ETF" },
  { symbol: "VGSH", name: "Vanguard Short-Term Treasury ETF", type: "ETF" },
  { symbol: "VGIT", name: "Vanguard Intermediate-Term Treasury ETF", type: "ETF" },
  { symbol: "VGLT", name: "Vanguard Long-Term Treasury ETF", type: "ETF" },
  { symbol: "BNDX", name: "Vanguard Total International Bond ETF", type: "ETF" },
  { symbol: "SCHZ", name: "Schwab U.S. Aggregate Bond ETF", type: "ETF" },
  { symbol: "MUB", name: "iShares National Muni Bond ETF", type: "ETF" },
  { symbol: "EMB", name: "iShares J.P. Morgan USD Emerging Markets Bond ETF", type: "ETF" },

  // Commodity & Real Asset ETFs
  { symbol: "GLD", name: "SPDR Gold Shares", type: "ETF" },
  { symbol: "IAU", name: "iShares Gold Trust", type: "ETF" },
  { symbol: "SLV", name: "iShares Silver Trust", type: "ETF" },
  { symbol: "GSG", name: "iShares S&P GSCI Commodity-Indexed Trust", type: "ETF" },
  { symbol: "DBC", name: "Invesco DB Commodity Index Tracking Fund", type: "ETF" },
  { symbol: "USO", name: "United States Oil Fund", type: "ETF" },
  { symbol: "UNG", name: "United States Natural Gas Fund", type: "ETF" },
  { symbol: "PDBC", name: "Invesco Optimum Yield Diversified Commodity Strategy", type: "ETF" },
  { symbol: "GLDM", name: "SPDR Gold MiniShares Trust", type: "ETF" },
  { symbol: "SGOL", name: "abrdn Physical Gold Shares ETF", type: "ETF" },

  // Thematic & Specialty ETFs
  { symbol: "ARKK", name: "ARK Innovation ETF", type: "ETF" },
  { symbol: "ARKG", name: "ARK Genomic Revolution ETF", type: "ETF" },
  { symbol: "ARKW", name: "ARK Next Generation Internet ETF", type: "ETF" },
  { symbol: "ARKF", name: "ARK Fintech Innovation ETF", type: "ETF" },
  { symbol: "ARKQ", name: "ARK Autonomous Technology & Robotics ETF", type: "ETF" },
  { symbol: "ICLN", name: "iShares Global Clean Energy ETF", type: "ETF" },
  { symbol: "TAN", name: "Invesco Solar ETF", type: "ETF" },
  { symbol: "QCLN", name: "First Trust NASDAQ Clean Edge Green Energy Index Fund", type: "ETF" },
  { symbol: "LIT", name: "Global X Lithium & Battery Tech ETF", type: "ETF" },
  { symbol: "BOTZ", name: "Global X Robotics & Artificial Intelligence ETF", type: "ETF" },
  { symbol: "ROBO", name: "Robo Global Robotics and Automation Index ETF", type: "ETF" },
  { symbol: "HACK", name: "ETFMG Prime Cyber Security ETF", type: "ETF" },
  { symbol: "CIBR", name: "First Trust NASDAQ Cybersecurity ETF", type: "ETF" },
  { symbol: "FINX", name: "Global X FinTech ETF", type: "ETF" },
  { symbol: "SKYY", name: "First Trust Cloud Computing ETF", type: "ETF" },
  { symbol: "WCLD", name: "WisdomTree Cloud Computing Fund", type: "ETF" },
  { symbol: "IGV", name: "iShares Expanded Tech-Software Sector ETF", type: "ETF" },
  { symbol: "SOXX", name: "iShares Semiconductor ETF", type: "ETF" },
  { symbol: "SMH", name: "VanEck Semiconductor ETF", type: "ETF" },
  { symbol: "XBI", name: "SPDR S&P Biotech ETF", type: "ETF" },
  { symbol: "IBB", name: "iShares Biotechnology ETF", type: "ETF" },
  { symbol: "ESGU", name: "iShares ESG Aware MSCI USA ETF", type: "ETF" },
  { symbol: "SUSA", name: "iShares MSCI USA ESG Select ETF", type: "ETF" },

  // Leveraged & Inverse ETFs (popular for trading)
  { symbol: "TQQQ", name: "ProShares UltraPro QQQ", type: "ETF" },
  { symbol: "SQQQ", name: "ProShares UltraPro Short QQQ", type: "ETF" },
  { symbol: "SPXL", name: "Direxion Daily S&P 500 Bull 3X Shares", type: "ETF" },
  { symbol: "SPXS", name: "Direxion Daily S&P 500 Bear 3X Shares", type: "ETF" },
  { symbol: "UPRO", name: "ProShares UltraPro S&P 500", type: "ETF" },
  { symbol: "QLD", name: "ProShares Ultra QQQ", type: "ETF" },
  { symbol: "SSO", name: "ProShares Ultra S&P 500", type: "ETF" },
  { symbol: "SH", name: "ProShares Short S&P 500", type: "ETF" },
  { symbol: "PSQ", name: "ProShares Short QQQ", type: "ETF" },
  { symbol: "VXX", name: "iPath Series B S&P 500 VIX Short-Term Futures ETN", type: "ETF" },
  { symbol: "UVXY", name: "ProShares Ultra VIX Short-Term Futures ETF", type: "ETF" },
  { symbol: "SVXY", name: "ProShares Short VIX Short-Term Futures ETF", type: "ETF" },
];

// Combined list of all curated stocks and ETFs
export const CURATED_ASSETS: CuratedAsset[] = [...SP500_STOCKS, ...POPULAR_ETFS];

// Quick lookup set for validation
export const CURATED_SYMBOLS = new Set(CURATED_ASSETS.map((a) => a.symbol));

/**
 * Check if a symbol is in our curated list
 */
export function isCuratedSymbol(symbol: string): boolean {
  return CURATED_SYMBOLS.has(symbol.toUpperCase());
}

/**
 * Get a curated asset by symbol
 */
export function getCuratedAsset(symbol: string): CuratedAsset | undefined {
  return CURATED_ASSETS.find((a) => a.symbol.toUpperCase() === symbol.toUpperCase());
}
